# Page settings
baseurl = "zeusricote.com"
title = "Korai Labs"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Korai"
  description = ""
  email = "zricote@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Korai Labs"
    home = "Home"
    work = "Work"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

  # Hero section
  [params.hero]
    title = "Do something you love."
    subtitle = 'Another free HTML5 bootstrap template by <a href="http://freehtml5.co/" target="_blank" title="Free HTML5 Bootstrap Templates">FREEHTML5.co</a> released under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Creative Commons 3.0</a><br> ported for Hugo by <a href="http://saey55.gitlab.io/pietercv" target="_blank">Pieter Saey</a>'

  # Intro section
  [params.intro]
  # (leave as is or remove if not needed)

  # Work section
  [params.work]
  # (leave as is or remove if not needed)

  # Testimonials section
  [params.testimonials]
  # (leave as is or remove if not needed)

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = """
I offer hands-on services in cybersecurity and offensive tooling:

- 🛠 Custom Recon/Exploit Tooling
- 🔍 Bug Bounty Investigations
- 🧪 Penetration Testing (Web, Mobile, RF)
- 📡 RF Analysis & Cloning (Proxmark3, SDR, etc.)
- 🔓 Physical Security Assessments (Lockpicking, Bypasses)
- 🕵️ OSINT Investigations (Scam tracking, digital trails , investigations)
- Custom physical access tools(lockpikcs, shims, tensors, lishi)

Prices are tailored to each client needs, so contact us if you need something
Want to work together or need help with a project? [Contact me](/contact/)
"""

    # You can keep existing items or remove if you want only the description:
    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains..."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains..."
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains..."
      icon = "icon-video2"

    [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains..."
      icon = "icon-monitor"


  # About section
  [params.about]
    enable = true
    title = "About"
    description = """
I’m **Zeus Ricote**, an independent cybersecurity researcher and bug bounty hunter.

My expertise lies in:

- Automating reconnaissance and vulnerability discovery
- Developing reliable pentesting tools
- Crafting custom exploits for real-world targets
- Sharing knowledge with the community

This site is my personal lab and journal — a place to share my projects, findings, and tools with fellow security enthusiasts.

Let’s push boundaries and raise the bar in ethical hacking.
"""

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]


  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = """
Feel free to reach out:

- 💬 Telegram: [@your_username](https://t.me/your_username)
- 💸 Support me: [Patreon](https://patreon.com/your_page)
- 📧 Email: [you@example.com](mailto:you@example.com)

I'm open to collaboration, questions, or freelance work.
"""

    # Keep these or update with your real contact info:
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
