// Generated by CoffeeScript 2.6.1
//Our App
var Post, Potion;

Post = class Post {
  constructor(path1, cb) {
    this.path = path1;
    Potion.github.repository.read(Potion.github.branch, this.path, (err, data) => {
      if (!err) {
        this.originalText = this.data = data;
        return typeof cb === "function" ? cb() : void 0;
      } else {
        return alert("There was an error in fetching this post");
      }
    });
  }

  //save:
  //Potion.
  isDraft() {
    return this.path.slice(0, 7) === "_drafts";
  }

  toHTML() {
    var converter, err, sourceText, yaml;
    converter = new Showdown.converter();
    try {
      yaml = YAML.loadFront(this.data);
      sourceText = yaml['__content'];
    } catch (error1) {
      err = error1;
      //if no YAML was found, just accept complete blob as markdown.
      sourceText = this.data;
    }
    return converter.makeHtml(sourceText);
  }

  hasChanged() {
    return this.originalText !== this.data;
  }

  title() {
    var error, title;
    try {
      title = YAML.loadFront(this.data)['title'];
      return title || "Untitled";
    } catch (error1) {
      error = error1;
      return "Untitled";
    }
  }

  save(cb) {
    var commitMessage, repo;
    if (!this.hasChanged()) {
      alert("No changes were made to the post.");
      return;
    }
    Potion.busy.show();
    repo = Potion.github.repository;
    commitMessage = "Updated " + this.title();
    return repo.write(Potion.github.branch, this.path, this.data, commitMessage, "utf-8", (err) => {
      Potion.busy.hide();
      if (!err) {
        alert("Post Saved");
      } else {
        alert("There was an error in saving your post. Are you logged in?");
      }
      return typeof cb === "function" ? cb() : void 0;
    });
  }

  publish() {
    var newPath;
    //Move it to _posts folder
    newPath = "_posts/" + Potion.Util.basename(this.path);
    return Potion.github.repository.move(Potion.github.branch, this.path, newPath, (err) => {
      if (!err) {
        alert("Post published");
      } else {
        alert("There was an error in publishing the post. Are you logged in?");
      }
      Potion.busy.hide();
      this.path = newPath;
      return Potion.controller.editor();
    });
  }

  unpublish() {
    var newPath;
    newPath = "_drafts/" + Potion.Util.basename(this.path);
    return Potion.github.repository.move(Potion.github.branch, this.path, newPath, (err) => {
      if (!err) {
        alert("Post moved to drafts.");
      } else {
        alert("There was an error in unpublishing the post. Are you logged in?");
      }
      Potion.busy.hide();
      this.path = newPath;
      return Potion.controller.editor();
    });
  }

  attachEvents() {
    //Add hooks here
    $('.admin').click(function(e) {
      return Potion.Util.showFiles();
    });
    $('#textpad').bind('keyup input propertychange', (e) => {
      this.data = $(e.target).val();
      return $('.title').text(this.title());
    });
    //Just make an updated commit
    $('.save').click((e) => {
      this.save();
      return this.originalText = this.data; //so that hasChanged() now returns false
    });
    $('.publish').click((e) => {
      if (Potion.post.hasChanged()) {
        return this.save(() => {
          Potion.busy.show();
          return this.publish();
        });
      } else {
        return this.publish();
      }
    });
    $('.unpublish').click((e) => {
      //This is same as publish, except we move to drafts this time
      if (Potion.post.hasChanged()) {
        return this.save(() => {
          Potion.busy.show();
          return this.unpublish();
        });
      } else {
        return this.unpublish();
      }
    });
    return $('.previewbtn').click((e) => {
      if (e.target.innerText === 'Preview') {
        $('#editor textarea').hide();
        $('#editor .preview').html(this.toHTML());
        $('#editor .preview').show();
        return $(e.target).text('Edit');
      } else {
        $('#editor .preview').hide();
        $('textarea').text(this.data).show();
        return $(e.target).text('Preview');
      }
    });
  }

};

Potion = {
  render: function(page, data = {}, controller) {
    var x;
    //order is DOM, TEMPLATE, DATA
    x = jade.render(document.body, page, data);
    return typeof controller === "function" ? controller(data) : void 0;
  },
  busy: {
    show: function() {
      return $('.busy').removeClass('hidden');
    },
    hide: function() {
      return $('.busy').addClass('hidden');
    }
  },
  controller: {
    //Login controller handles login information
    login: function() {
      Potion.fixLayout();
      $('#password,#username').keyup(function(e) {
        if (e.keyCode === 13) {
          return $('#login').click();
        }
      });
      return $('#login').click(function() {
        var after, password, user, username;
        Potion.busy.show();
        username = $('#username').val();
        password = $('#password').val();
        Potion.github = new Github({
          username: username,
          password: password,
          auth: "basic"
        });
        user = Potion.github.getUser();
        after = function(err, repos) {
          if (!err) {
            Potion.busy.hide();
            return Potion.controller.choose(repos);
          } else {
            return $('.notice').html("<p>There was an error while logging in to your account. Please check your username (and password). Please use your password if Potion is hitting the Github API rate-limits.").addClass('error');
          }
        };
        //We use different functions based on
        //whether we have password or not
        if (password.length > 0) {
          return user.repos(after);
        } else {
          //Our github lib doesn't support this
          //So we freestyle and use JQuery
          return $.getJSON("https://api.github.com/users/" + username + "/repos?type=all&per_page=1000&sort=updated", function(data) {
            return after(null, data);
          }).error(function() {
            return after(true, null);
          });
        }
      });
    },
    //Choose a repository and a branch
    choose: function(repos) {
      Potion.render("choose", {
        list: repos
      });
      return $('#continue').click(function() {
        Potion.github.repo = $('#reponame').val().split('/')[1];
        Potion.github.user = $('#reponame').val().split('/')[0];
        Potion.github.branch = $('#branchname').val();
        //We store this data
        //Make requests to github to get the list of files
        Potion.busy.show();
        return Potion.Util.showFiles();
      });
    },
    admin: function(files) {
      Potion.fixLayout();
      $(".right-pane, .options .btn[data-action='postsActive']").removeClass('active');
      $(".center-pane, .options .btn[data-action='draftsActive']").addClass('active');
      $(".file a").click(function(e) {
        var draft, filePath;
        filePath = e.target.getAttribute('data-path');
        if (e.target.getAttribute('data-draft') === "true") {
          draft = true;
        }
        //We send the draft data to make sure that the buttons are correct
        Potion.busy.show();
        return Potion.post = new Post(filePath, function() {
          return Potion.controller.editor();
        });
      });
      $('#newPostBtn').click(function(e) {
        var postFilePath;
        postFilePath = "_drafts/" + Potion.Util.titleToPath($('#newPostTitle').val() + ".md");
        //We create a blank file first and then allow the user to edit it
        Potion.busy.show();
        Potion.defaultYAML.title = $('#newPostTitle').val();
        return Potion.github.repository.write(Potion.github.branch, postFilePath, YAML.createFront(Potion.defaultYAML), "New blank post", "utf-8", function(err) {
          if (err) {
            Potion.busy.hide();
            return alert("There was an error in creating the file. Are you logged in?");
          } else {
            return Potion.post = new Post(postFilePath, function() {
              return Potion.controller.editor();
            });
          }
        });
      });
      return $('#newPostTitle').keyup(function(e) {
        if (e.keyCode === 13 && e.target.value.length > 0) {
          return $('#newPostBtn').click();
        }
      });
    },
    editor: function() {
      return Potion.github.repository.read(Potion.github.branch, Potion.post.path, function(err, data) {
        Potion.busy.hide();
        //Now we render the editor
        return Potion.render("editor", Potion.post, function() {
          Potion.post.attachEvents();
          return Potion.fixLayout();
        });
      });
    }
  },
  init: function() {
    Potion.render("login", {}, Potion.controller.login);
    // Default .active on mobile layouts
    if ($(".options.onMobile").css('display') === 'block') {
      $("button.btn").eq(0).addClass('active');
      $(".left-pane").addClass('active');
    }
    return $(document).on('click', '.options .btn', function() {
      var action;
      action = $(this).attr('data-action');
      if (action === 'draftsActive') {
        $(".right-pane, .options .btn[data-action='postsActive']").removeClass('active');
        $(".center-pane, .options .btn[data-action='draftsActive']").addClass('active');
      }
      if (action === 'postsActive') {
        $(".center-pane, .options .btn[data-action='draftsActive']").removeClass('active');
        return $(".right-pane, .options .btn[data-action='postsActive']").addClass('active');
      }
    });
  },
  fixLayout: function() {
    var ratio;
    if ($("textarea").length) {
      ratio = 900 / document.width;
      $("textarea").css({
        'left': (document.width - 900) / 2,
        'right': (document.width - 900) / 2,
        'max-width': parseInt(document.width * ratio).toString() + 'px'
      });
    }
    if ($(".login-div").length) {
      // Scrollbar Fix
      $(".login-div").css({
        'height': (document.height - $(".top-line")[0].offsetHeight).toString() + 'px'
      });
    }
    if ($(".center-pane ul.drafts-list").length) {
      $(".center-pane ul.drafts-list").css({
        'height': (document.height - 106).toString() + 'px'
      });
    }
    if ($(".right-pane ul.published-list").length) {
      return $(".right-pane ul.published-list").css({
        'height': (document.height - 60).toString() + 'px'
      });
    }
  },
  Util: {
    getFiles: function(cb) {
      Potion.github.repository = Potion.github.getRepo(Potion.github.user, Potion.github.repo);
      Potion.github.repository.read(Potion.github.branch, "_default.yml", function(err, data) {
        if (err) {
          return Potion.defaultYAML = {
            title: "Untitled",
            layout: "default"
          };
        } else {
          return Potion.defaultYAML = YAML.parse(data);
        }
      });
      return Potion.github.repository.getTree(Potion.github.branch + '?recursive=true', function(err, data) {
        var drafts, file, i, len, posts;
        if (!err) {
          drafts = [];
          posts = [];
          for (i = 0, len = data.length; i < len; i++) {
            file = data[i];
            if (file.path.slice(0, 8) === "_drafts/") {
              file.name = Potion.Util.pathToName(file.path);
              drafts.push(file);
            }
            if (file.path.slice(0, 7) === "_posts/" || file.path.slice(0, 14) === "source/_posts/") {
              file.name = Potion.Util.pathToName(file.path);
              posts.push(file);
            }
          }
          if (posts.length === 0 && drafts.length === 0) {
            err = true;
          }
          //Reverse the arrays as they are in ascending order by date
          posts = posts.reverse();
          drafts = drafts.reverse();
        }
        return typeof cb === "function" ? cb(err, drafts, posts) : void 0;
      });
    },
    showFiles: function() {
      return Potion.Util.getFiles(function(err, drafts, posts) {
        Potion.busy.hide();
        if (err) {
          return $('.notice').addClass('error').html("<p>There was an error while fetching this repository. Are you sure its a jekyll repo?</p>");
        } else {
          return Potion.render("admin", {
            drafts: drafts,
            posts: posts
          }, Potion.controller.admin);
        }
      });
    },
    pathToName: function(path) {
      var err, name;
      //Get the basename
      path = Potion.Util.basename(path);
      //Remove the extension
      path = path.substr(0, path.lastIndexOf('.')) || path;
      try {
        //remove the date
        name = path.match(/\d{4}-\d{1,2}-\d{1,2}-(.*)/)[1];
      } catch (error1) {
        err = error1;
        //drafts are sometimes date-less in filenames
        //This is in-fact, what jeykll recommends for drafts.
        name = path;
      }
      //Auto-return
      return name.replace(/-/g, ' ').toTitleCase();
    },
    basename: function(path) {
      return path.split('/').reverse()[0];
    },
    titleToPath: function(title) {
      return title.replace(/\ /g, '-').toLowerCase().replace(/[^-.\w\s]/gi, '');
    }
  }
};

$(document).ready(function() {
  Potion.init();
  return $(window).on('resize', function(e) {
    return Potion.fixLayout();
  });
});
